SET IDENTITY_INSERT [dbo].[Menus] ON
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1, 4, N'Salad', N'Salad is rich in a variety of vegetables', 34, N'../../Image/First/148207351_c8ff08315a_z.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (2, 2, N'Tomato juice
', N'Natural juice squeezed from fresh tomatoes', 18, N'../../Image/Drink/tomatoJuice.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (3, 2, N'Wine', N'A glass of wine from the selected wines', 45, N'../../Image/Drink/wine.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (4, 2, N'Cappuccino', N'Hot drink based on milk or soy', 19, N'../../Image/Drink/cafe.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (5, 2, N'Flavoured water', N'Flavored water is served with fruit pieces and ice cubes', 15, N'../../Image/Drink/water.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (6, 2, N'Fruit shake', N'Fruit smoothies based on milk or water
With seasonal fruit', 25, N'../../Image/Drink/fruitShake.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (7, 2, N'Beer', N'Selection of beers', 35, N'../../Image/Drink/beer.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (10, 1, N'Alphors', N'Calrfu cookies', 20, N'../../Image/Desserts/15204286153_99b7c95f11_z.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (11, 1, N'Fruit salad', N'Salad', 20, N'../../Image/Desserts/15204309883_f6e00423e6_z.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (34, 1, N'Cherry Cake', N'A marble cake with sweet cherries', 16, N'../../Image/Desserts/15800054886_1770404232_z.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (35, 1, N'Brownies
', N'Chocolate cake with nuts', 22, N'../../Image/Desserts/15800058956_1fac0a62d4_z.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (36, 1, N'Watermelon', N'Cold and refreshing watermelon', 15, N'../../Image/Desserts/15821850321_00a32d97f5_z.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (37, 1, N'Pancake', N'Pancakes with ice cream and whipped cream', 23, N'../../Image/Desserts/15638298618_104af94267_z.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (38, 1, N'Mini fruit pie', N'Mini fruit pie 3 units', 25, N'../../Image/Desserts/15638862700_e0f3e3a467_z.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1011, 1, N'Mini blooberies pie', N'Mini blooberies pie 3 units', 25, N'../../Image/Desserts/15825263582_b0a06d4a18_z.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1012, 1, N'Muss ', N'Vanilla muss with forest fruits', 30, N'../../Image/Desserts/27504783974_4b24c7ac07_z.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1013, 3, N'Filmmaking', N'Very tasty Bukhari dish comes frozen
', 16, N'../../Image/pilimeni.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1015, 2, N'Soda', N'Cool and refreshing cold drink', 10, N'../../Image/Drink/water-glass-heat-drink-161425.jpeg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1016, 2, N'Cocktail', N'Cold drink consisting of exotic fruits', 15, N'../../Image/Drink/SplitShire-4229-1024x683.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1017, 2, N'Water', N'Cold water served with lemon pieces and ice cubes', 12, N'../../Image/Drink/mineral-water-lime-ice-mint-158821.jpeg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1018, 4, N'Fries', N'Hot and crisp potatoes', 20, N'../../Image/First/15638300758_87c9fb6c34_z.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1019, 4, N'Bread', N'Hot baked bread', 14, N'../../Image/First/15638301508_723bda456e_z.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1020, 4, N'Omelet', N'An omelette made of egg and seasoned with rich and healthy spices alongside potatoes and tomatoes', 17, N'../../Image/First/15821826601_bbe93df693_z.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1021, 4, N'Fish', N'A pastry filled with rice and fish', 23, N'../../Image/First/pexels-photo-213939.jpeg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1022, 4, N'Rice', N'Rice seasoned with spices and vegetables', 25, N'../../Image/First/pexels-photo-221091.jpeg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1023, 4, N'Sweet potatoes', N'Fried sweet potatoes with slices of cucumbers', 20, N'../../Image/First/pexels-photo-273848.jpeg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1024, 4, N'Potato pastry', N'A potato pastry with mushroom sauce next to fresh cut vegetables', 22, N'../../Image/First/pexels-photo-343812.jpeg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1025, 4, N'Pieces of bread', N'Pieces of baked bread beside dips', 23, N'../../Image/First/SplitShire-5622-1024x683.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1026, 3, N'Pizza', N'Pizza meal', 50, N'../../Image/Main/Pizza.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1027, 3, N'Ravioli', N'Ravioli meal', 30, N'../../Image/Main/Ravioli.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1028, 3, N'PastaWithChees', N'PastaWithChees', 45, N'../../Image/Main/PastaWithChees.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1029, 3, N'Sushi', N'Sushi', 30, N'../../Image/Main/SplitShire-9737-1024x683.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1030, 3, N'Spagehetti', N'Spagehetti', 35, N'../../Image/Main/SplitShire_IMG_7416-1024x683.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1031, 3, N'Lazania', N'Lazania', 30, N'../../Image/Main/Lazania.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1032, 3, N'Stir fried chicken', N'Stir fried chicken', 40, N'../../Image/Main/28296627992_b2419c930f_z.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1033, 3, N'Antipasti', N'Antipasti', 35, N'../../Image/Main/28039109381_0e41418f02_z.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1034, 3, N'Tomato sauce', N'Tomato sauce', 25, N'../../Image/Main/15825261892_32bd93cf52_z.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1035, 3, N'Sushi Salmon', N'Sushi Salmon', 33, N'../../Image/Main/15821863691_f22cfa6200_z.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1036, 3, N'Vegetables in the oven
', N'Vegetables in the oven
', 30, N'../../Image/Main/15638300698_18edde5ab3_z.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1037, 3, N'Nocchi', N'Nocchi', 34, N'../../Image/Main/15637936889_7127ee84bd_z.jpg')
INSERT INTO [dbo].[Menus] ([IdMenu], [Categorya], [NameDose], [Description], [Price], [ImageUri]) VALUES (1038, 3, N'Israeli salad', N'Israeli salad', 33, N'../../Image/Main/15637912959_28a4eb9824_z.jpg')
SET IDENTITY_INSERT [dbo].[Menus] OFF
